name: Test, Upload artifact

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, package and
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context:
          push: true
          tags: adpndt/meeting-buddy:$(git rev-parse --short HEAD)